logger:
  api_register: false
  request_stack_error: true

server:
  host: "0.0.0.0"
  type: "http"
  http:
    port: 25565
  https:
    port: 25566
    cert: "./data/ssl/fullchain.pem"
    key: "./data/ssl/privkey.key"

database:
  type: "sqlite"
  sqlite:
    path: "./data/db/sky.db"
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: ""
    name: "xysky"
    connectionLimit: 10
    queueLimit: 0
    idleTimeout: 60000
    maxIdle: 5
    connectTimeout: 10000
    ssl: false
  migrations:
    runOnStartup: true

jwt:
  secret: "1234cfe08b8e9a522229e4663e4c1234"
  expiresIn: "7d"

game:
  initialCurrency:
    candles: 5
    hearts: 5
    season_candle: 5
    prestige: 5
  socialFeed:
    socialFeedExpireDays: 30
    uri: "serveruri.cn"
    curatedFeeds:
      defaultFillPriority: [ "friends", "followed", "public", "local" ]
      friendsQueryLimit: 2000
      followedQueryLimit: 2000
      publicQueryLimit: 4000
      localQueryLimit: 4000
      maxBucketCount: 200
      allowCrossRingFill: true
      allowCrossBucketFill: true
      defaultInnerRadius: 16
      defaultOuterRadius: 0
      defaultVerticalRadius: 24
      scoreAlgoVersion: "v1a32"
      totalAvailableResultsMode: "filtered_unique"
      liteFields:
      - "social_feed_id"
      - "user_id"
      - "author_id"
      - "pool_type"
      - "pool_name"
      - "level_id"
      - "create_at"
      - "expire_at"
      - "message"
      - "content_type"
      - "content"
      - "resource_id"
      - "recording_id"
      - "tags"
      - "reactions"
      - "state"
      - "comments_enabled"
      - "location"
      - "local_creation"
      - "followed"
      - "friend"

udp:
  uri: "100.64.15.8:19132"

cdn:
  host: "sky.resources.cdn.thatgamecompany.com"
  prefix: ""

mqtt:
  brokerUrl: ""
  username: ""
  password: ""

contentModeration:
  enabled: false
  blockMode: "direct"
  replacementChar: "*"
  logViolations: true
